# Generated by Django 5.0.4 on 2024-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
